### ISSUE TITLE
cannot download vgg16_tf_dim_ordering_notop.h5 file.

### ISSUE THREAD

**Issue by TriLoo** [Arsey/keras-transfer-learning-for-oxford102#6]
Hi Arsey, 
    When I typed "python train.py" , this problem arisen that connect failed to download above weight file.
    So I tried to download it from github and place it under the same path with vgg16 models, but failed downloading again, any advices?
    thank you

**Comment by Arsey** [comment]
it looks like you have TensorFlow as backend. Can you switch (https://keras.io/backend/#switching-from-one-backend-to-another) to Theano and try it again?

**Comment by TriLoo** [comment]
I am using TensorFlow as backend exactly......   I will switch to Theano and try it again. Thanks for your response :+1:

**Comment by TriLoo** [comment]
well, I just tried this method, but doesn't work ... : (

**Comment by Arsey** [comment]
@TriLoo show me the error stack

**Comment by TriLoo** [comment]
Uhm, it's another error this time

log info : 
Using Theano backend.
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    bottlenecks.save_bottleneck_features()
  File "/home/smher/Desktop/ML_Work/keras-transfer-learning-for-oxford102-master/bottlenecks.py", line 13, in save_bottleneck_features
    model = VGG16(weights='imagenet', include_top=False)
  File "/home/smher/anaconda2/lib/python2.7/site-packages/keras/applications/vgg16.py", line 155, in VGG16
    model.load_weights(weights_path)
  File "/home/smher/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2695, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/smher/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/smher/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (-------src-dir-------/h5py/h5f.c:1816)
IOError: Unable to open file (Truncated file: eof = 1040384, sblock->base_addr = 0, stored_eoa = 58889256)

**this is my keras config file**:
{
    "image_dim_ordering": "tf", 
    "epsilon": 1e-07, 
    "floatx": "float32", 
    "backend": "theano"
}

**Comment by Arsey** [comment]
@TriLoo I bet it's something  wrong with your weights file. Try to download it again. Simply rename or delete ~/.keras/models dir

**Comment by TriLoo** [comment]
Well, my problem is I cannot download the weights files. my meaning is that the program work correctlly, but I cannot get the weight file from internet......

**Comment by Arsey** [comment]
pretty strange, as I was able to download them from scratch a few minutes ago

**Comment by Arsey** [comment]
@TriLoo hey I've just shared the weights you need via Dropbox - https://www.dropbox.com/s/yxmmlv5f4vljafs/vgg16_weights_th_dim_ordering_th_kernels_notop.h5?dl=0

**Comment by TriLoo** [comment]
@Arsey  I just clicked the website you shared to me, but I cannot connect it : (. would you please email this file to me directly ?   my email: song_mh@yeah.net   That would be of great help to my work.
